[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://fitnessrepublic.co.uk"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
	providers = [
		"google"
	]

	[[redirects]]
  from = "/the-team"
  to = "/team"
  status = 301
  force = false
  query = {path = ":path"}
	[[redirects]]
	from = "/free-pass"
  to = "/membership"
  status = 301
  force = false
  query = {path = ":path"}
	[[redirects]]
	from = "/students"
  to = "/membership"
  status = 301
  force = false
  query = {path = ":path"}
	[[redirects]]
	from = "/contact"
  to = "/"
  status = 301
  force = false
  query = {path = ":path"}
		[[redirects]]
	from = "/personal-training"
  to = "/training"
  status = 301
  force = false
  query = {path = ":path"}


